### ISSUE TITLE
About the moving speed

### ISSUE THREAD

**Issue by giser** [manila/googlemaps-snake-hacks#1]
Thank you for developing the bot:)
Is it possible to let the train moving faster?

**Comment by manila** [comment]
Great Idea, I'll see if I can figure that out. Stay tuned.

**Comment by manila** [comment]
Done. I've added a "Speed Hack" bookmarklet.

[https://github.com/manila/googlemaps-snake-bot/blob/master/googlemaps-snake-speedhack-bookmarklet](https://github.com/manila/googlemaps-snake-bot/blob/master/googlemaps-snake-speedhack-bookmarklet)
